name: My First Workflow

on:
  pull:
    branches: [ "main" ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkeout Repo
        uses: actions/checkout@v4
      ##multi-line-statements
      - name: Welcome message
        run: |
         echo "My first github actions job"
         ls -ltr
         cat README.md
      - name: Executing Bash script
        run: |
         chmod +x new.sh
         ./new.sh

      
      # - name: Welcome message
      #   run: echo "My first github actions job"
      
      # - name: List and Read files
      #   run: ls -ltr
        
      # - name: Read files
      #   run: cat README.md

